version: '3.8'

services:
  db:
    image: postgres:13
    container_name: empodera-db
    environment:
      POSTGRES_USER: empodera
      POSTGRES_PASSWORD: empodera
      POSTGRES_DB: empodera_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  db_data:
